config/routes.rb
Rails.application.routes.draw do
  get 'accounts/manage'
  get 'accounts/manage/:user/:pass' =>'accounts#manage'

  get 'accounts/regist'
  post 'accounts/regist'

  get 'accounts/list'
  post 'accounts/list'

  post 'accounts/manage'

  get 'accounts/delete/:account', to: 'accounts#delete'
  post 'accounts/delete'

  get 'accounts/check'
  get 'accounts/check/:user/:pass' =>'accounts#check'

  root :to => 'accounts#manage'

  get 'accounts/update'
  post 'accounts/update'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def check
    tuser = params[:user]
    tpass = params[:pass]

    @user = 'NG'
    @pass = 'NG'
    pa = Account.find_by(user:tuser)
    if pa.nil?
    else
      if pa.availability == true then
        @user = 'OK'
        if pa.pass == tpass
          @pass = 'OK'
        end
      end
    end
  end

  def manage
    if request.post? then

    else
      tuser = params[:user]
      tpass = params[:pass]

      @user = 'NG'
      @pass = 'NG'
      pa = Account.find_by(user:tuser)
      if pa.nil?
      else
        @user = 'OK'
        if pa.pass == tpass
          @pass = 'OK'
        end
      end
    end
  end

  def regist
    if request.post? then
      account = params[:account]
      pass = params[:password]
      Account.create(user:account, pass:pass,availability:true)
    end
  end

  def delete
    if request.get? then
      account = params[:account]
      if account != nil then
        ac = Account.find_by(user:account)
        ac.destroy
      end
    end
    redirect_to '/accounts/list'
  end

  def update
    if request.post? then
      if params[:commit] == "検索" then
        if params[:account] != "" then
          account = params[:account]
          if Account.find_by(user:account) != nil then
            @user = Account.find_by(user:account).user
            @pass = Account.find_by(user:account).pass
            @avail = Account.find_by(user:account).availability
            @msg = 'ヒットしました'
          else
            @msg = '該当のアカウントはありません'
          end
        end
      else
        if params[:commit] == "更新" then
          if params[:new_account] != "" then
            new_account = params[:new_account]
            new_pass = params[:new_pass]
            new_avail = params[:new_avail]
            obj = Account.find_by(user:new_account)
            obj.update(user: new_account,pass:new_pass,availability:new_avail)
          end
        end
      end
    end
  end

  def list
    @data=Array.new
    if request.post? then
      if params[:check] == "1234" then
        tables = Account.all
        @data = tables
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/check.html.erb
<h1>アカウント管理ツール</h1>
<p>エクセルツールのアカウントの結果</p>
<br>

<p>user:<%= @user %></p>
<p>pass:<%= @pass %></p>

app/views/accounts/list.html.erb
<h1>アカウント情報の確認</h1>
<br>
<%= link_to 'トップページ', {action:"manage"} %>
<br>
<%= form_tag({controller: "accounts", action: "list"}) do %>
  <p>閲覧パスワード：</p><%= text_field_tag("check") %>
  <%= submit_tag("表示") %>
<% end %>
<br>
<br>
<table>
  <tr>
    <th>アカウント</th><th>パスワード</th><th>有効性</th><th>アクション</th>
  </tr>
  <% @data.each do |obj| %>
  <tr>
    <td><%= obj.user %></td>
    <td><%= obj.pass %></td>
    <td><%= obj.availability %></td>
    <td><%= link_to '削除', controller:'accounts',action:'delete', :account => obj.user %></td>
  </tr>
  <% end %>
</table>

app/views/accounts/manage.html.erb
<h1>アカウント管理ツール</h1>
<p>エクセルツールのアカウントを管理</p>
<br>
<%= link_to '新規アカウントの登録', accounts_regist_path %>
<br>
<br>
<%= link_to '既存アカウントの更新', accounts_update_path %>
<br>
<br>
<%= link_to '登録アカウントの確認', accounts_list_path %>

app/views/accounts/regist.html.erb
<h1>アカウント情報の登録</h1>
<br>
<%= link_to 'アカウントの更新', {action:"update"} %>
&nbsp;
<%= link_to 'トップページ', {action:"manage"} %>
<br>
<%= form_tag(controller: "accounts", action: "regist") do %>
  <p>アカウント名：</p><%= text_field_tag("account") %>
  <p>パスワード：</p><%= text_field_tag("password") %>
  <%= submit_tag("登録") %>
<% end %>

<br>
<br>
<p>登録情報</p>
<%= @data %>
<br>

app/views/accounts/update.html.erb
<h1>アカウント情報の更新</h1>
<br>
<%= link_to 'アカウントの登録', {action:"regist"} %>
&nbsp;
<%= link_to 'トップページ', {action:"manage"} %>
<br>
<%= form_tag(controller: "accounts", action: "update") do %>
  <p>アカウント名：</p><%= text_field_tag("account") %>
  <%= submit_tag("検索") %>
<% end %>
<br>
<%= @msg %>
<br>
<p>登録情報の更新</p>
<%= form_tag(controller: "accounts", action: "update") do %>
<table>
  <tr>
    <th>登録情報</th>
    <th>現在</th>
    <th>変更後</th>
  </tr>
    <th>アカウント</th>
    <td><%= @user %></td>
    <td><%= text_field_tag("new_account",@user) %></td>
  <tr>
    <th>パスワード</th>
    <td><%= @pass %></td>
    <td><%= text_field_tag("new_pass",@pass) %></td>
  </tr>
  <tr>
    <th>有効性</th>
    <td><%= @avail %></td>
    <td><%= select_tag("new_avail",options_for_select(['true','false'])) %></td>
  </tr>
</table>
<br>
<%= submit_tag("更新") %>
<% end %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExcelAccountManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/regist.html.erb
<%= stylesheet_link_tag "regist", :media => "all" %>